export interface ProjectPhase {
  icon: string;
  label: string;
  status: string;
  statusBg: string;
  statusColor: string;
}

export interface ProjectSkill {
  name: string;
  pct: number;
}

export interface ProjectKPI {
  val: string;
  label: string;
}

export interface Project {
  id: number;
  title: string;
  status: string;
  statusClass: string;
  category: string;
  bgGradient: string;
  image: string;
  imagePosition?: string;
  detailImagePosition?: string;  // independent position for the detail/fullscreen hero
  imageFit?: string;             // CSS object-fit: 'cover' (default), 'contain', 'fill', 'scale-down'
  icon: string;
  completion: number;
  tags: string[];
  kpis: ProjectKPI[];
  overview: string;
  challenge: string;
  phases: ProjectPhase[];
  outcomes: string[];
  skills: ProjectSkill[];
  quote: { text: string; attr: string };
  desc: string;
  stats: { icon: string; label: string }[];
  progressLabel: string;
  progressValue: string;
  deliveryDate: string;
  galleryImages: string[];
}

export interface Study {
  id: number;
  title: string;
  category: string;
  institution: string;
  period: string;
  bgGradient: string;
  image: string;
  imagePosition?: string;
  detailImagePosition?: string;  // independent position for the detail/fullscreen hero
  imageFit?: string;             // CSS object-fit: 'cover' (default), 'contain', 'fill', 'scale-down'
  icon: string;
  score: string;
  scorePct: number;
  tags: string[];
  overview: string;
  thesis: string;
  modules: string[];
  skills: ProjectSkill[];
  highlight: string;
  desc: string;
}

export const projects: Project[] = [
  {
    id: 0,
    title: 'AI Persona Agent',
    status: 'Delivered',
    statusClass: 'chip-delivered',
    category: 'e-Commerce \u00b7 Plexus Worldwide',
    bgGradient: 'linear-gradient(135deg,#0D7A87 0%,#1B9AAA 60%,#2BBDCF 100%)',
    image: 'https://cdn.myportfolio.com/abc1e0ab-7370-4502-8c78-92428397bf66/ee047e61-2020-4959-a701-7b0687bb93a3.png?h=2c211f1fe6dac603c6715a7ca828d235',
    imagePosition: 'left',
    detailImagePosition: 'left top',
    imageFit: 'cover',
    icon: 'phone_iphone',
    completion: 100,
    tags: ['Claude AI','Gemini API','Figma','Entrepreneurial networking','Targeted marketing'],
    desc: 'Delivered primary definitions of target customers to build marketing, comms, define product strategy, and leverage BI to advise data-backed decisions',
    progressLabel: 'Completion',
    progressValue: '100%',
    stats: [
      { icon: 'groups', label: 'Whole Business impact' },
      { icon: 'schedule', label: '6 months' },
      { icon: 'trending_up', label: '+38% Conversion Rates' },
    ],
    kpis: [
      { val:'200k', label:'Active Personas' },
      { val:'100%', label:'Customer Capture' },
      { val:'4 mo', label:'Delivery Time' },
      { val:'\u2605\u2605\u2605\u2605\u2605', label:'Customer Feedback' },
    ],
    overview: 'An AI-assisted persona generation platform built on live business intelligence data from active e-commerce and affiliate network entrepreneurs. The system transformed fragmented customer knowledge into structured behavioral, demographic, and psychological insights\u2014enabling teams across sales, marketing, customer service, and leadership to understand not just who customers were, but how and why they made decisions.',
    challenge: 'Within four months of adoption, insights generated by the platform directly informed targeted marketing campaigns and customer engagement strategies that reversed a negative profit trajectory. The business moved from a \u201317% margin to a +2% margin, improved customer retention and subscription renewals, increased average cart size, and reduced friction for entrepreneurs onboarding new customers\u2014demonstrating how thoughtfully applied generative AI can drive measurable commercial outcomes when grounded in meaningful design and research principles.',
    phases: [
      { icon:'search', label:'Resolution Alignment', status:'Done', statusBg:'rgba(76,175,130,0.12)', statusColor:'#2E7D53' },
      { icon:'architecture', label:'Systems Architecture', status:'Done', statusBg:'rgba(76,175,130,0.12)', statusColor:'#2E7D53' },
      { icon:'dashboard_customize', label:'Web App build (v1.0)', status:'Done', statusBg:'rgba(76,175,130,0.12)', statusColor:'#2E7D53' },
      { icon:'rocket_launch', label:'Phased CDCI over 4 weeks', status:'Done', statusBg:'rgba(76,175,130,0.12)', statusColor:'#2E7D53' },
      { icon:'auto_awesome', label:'Orginizational On-boarding', status:'Done', statusBg:'rgba(76,175,130,0.12)', statusColor:'#2E7D53' },
    ],
    outcomes: [
      'Reversed negative profitability; from a \u201317% operating margin to +2% within four months.',
      '15% customer retention and subscription renewals from real, actionable behavioral insights.',
      '10% increased average cart size and customer lifetime value.',
      'Reduced customer acquisition friction and onboarding; enrolling new customers, by proactively addressing needs.',
      'Scaled organization awareness of customers, empowering ~40 users across sales, customer service, field development, and executive leadership.',
    ],
    skills: [
      { name:'Executive Communications', pct:100 }, { name:'system & platform Architecture design', pct:95 }, { name:'Behavioral and Psychological research', pct:80 },
      { name:'Agentic AI modeling', pct:88 }, { name:'Project Leadership', pct:90 }, { name:'Strategic Planning', pct:85 },
    ],
    quote: { text:'This platform fundamentally changed how we understand and engage our customers. Within four months, it enabled more precise targeting and smarter interactions that helped move our operating margin from \u201317% to +2%, while strengthening customer trust and long-term engagement', attr:'\u2014 Chief Marketing Officer | Plexus Worldwide' },
    deliveryDate: 'Q4 2024',
    galleryImages: [
      'https://images.unsplash.com/photo-1768987439382-894ea4e2a736?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtb2JpbGUlMjBhcHAlMjBzaG9wcGluZyUyMGVjb21tZXJjZSUyMGludGVyZmFjZXxlbnwxfHx8fDE3NzIzNDQ5Mzl8MA&ixlib=rb-4.1.0&q=80&w=1080',
      'https://images.unsplash.com/photo-1682941664177-7920d0e59418?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxBSSUyMGNoYXRib3QlMjBwZXJzb25hJTIwdXNlciUyMHJlc2VhcmNofGVufDF8fHx8MTc3MjM0NDkzOXww&ixlib=rb-4.1.0&q=80&w=1080',
      'https://images.unsplash.com/photo-1542744094-24638eff58bb?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxlY29tbWVyY2UlMjBwcm9kdWN0JTIwc3RyYXRlZ3klMjB3aGl0ZWJvYXJkfGVufDF8fHx8MTc3MjM0NDk0MHww&ixlib=rb-4.1.0&q=80&w=1080',
      'https://images.unsplash.com/photo-1735639013995-086e648eaa38?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx0ZWFtJTIwd29ya3Nob3AlMjBjb2xsYWJvcmF0aW9uJTIwcGxhbm5pbmd8ZW58MXx8fHwxNzcyMzQ0OTQwfDA&ixlib=rb-4.1.0&q=80&w=1080',
    ],
  },
  {
    id: 1,
    title: 'Design System Architect',
    status: 'Delivered',
    statusClass: 'chip-delivered',
    category: 'Product Buidling \u00b7 Plexus Worldwide',
    bgGradient: 'linear-gradient(135deg,#050505 0%,#1A2A2E 60%,#1B9AAA 100%)',
    image: 'https://cdn.myportfolio.com/abc1e0ab-7370-4502-8c78-92428397bf66/add554db-a2df-4e15-9a20-0dfde63d289f.png?h=5240e27f8891c66968c5e4a1610fe67c',
    imagePosition: 'center',
    detailImagePosition: 'top',
    imageFit: 'cover',
    icon: 'dashboard',
    completion: 100,
    tags: ['Systems Architecture','Scalable Patterns','Delivery consistencies','Operational Design Excellence','Business-Aligned UX'],
    desc: 'Designed, built, and deployed modern design system adopted by marketing and product teams, reducing delivery time by ~35%.',
    progressLabel: 'Completion',
    progressValue: '100%',
    stats: [
      { icon: 'storage', label: 'Operational Stategy' },
      { icon: 'speed', label: 'Fast hand-offs' },
      { icon: 'savings', label: 'Reduce Labor' },
    ],
    kpis: [
      { val:'50%', label:'reduction in time to deliver' },
      { val:'5', label:'Designers impacted' },
      { val:'3\u00d7', label:'more design deliverables' },
      { val:'$370K', label:'designer hours saved' },
    ],
    overview: 'Delivered as a hybrid "greenfield" and progressive migration, the system lives in Figma and is referenced directly in Contentful, enabling designers, engineers, and leaders to operate from a shared source of truth. Its adoption materially improved delivery speed, design quality, and team confidence\u2014transforming design from a reactive service into a scalable, strategic capability.',
    challenge: 'I architected and led the delivery of a comprehensive design system to modernize a fragmented and outdated web and portal experience spanning marketing, sales, customer-facing reports, and internal communications tools. The goal was not only visual renewal, but the creation of a durable system that improved consistency, usability, and execution speed\u2014that also aligned day-to-day design decisions more closely with business outcomes and field development needs.',
    phases: [
      { icon:'storage', label:'Problem Framing & Alignment', status:'Done', statusBg:'rgba(76,175,130,0.12)', statusColor:'#2E7D53' },
      { icon:'api', label:'System Architecture & Governance', status:'Done', statusBg:'rgba(76,175,130,0.12)', statusColor:'#2E7D53' },
      { icon:'bar_chart', label:'Performance Design & Governance', status:'Done', statusBg:'rgba(76,175,130,0.12)', statusColor:'#2E7D53' },
      { icon:'notifications_active', label:'Component & Pattern Designs', status:'Done', statusBg:'rgba(76,175,130,0.12)', statusColor:'#2E7D53' },
      { icon:'share', label:'Adoption, Enablement & Iteration', status:'Done', statusBg:'rgba(76,175,130,0.12)', statusColor:'#2E7D53' },
    ],
    outcomes: [
      'Established consistent design patterns across products, eliminating inconsistencies between designers and teams.',
      'A shared source of truth that clarified scope, deliverables, and expectations for design artifacts.',
      'Aignment between UX strategy and business goals by embedding intent directly into system standards.',
      'Confidence and autonomy of junior and mid-level designers through clear, repeatable patterns.',
      'Gained executive trust in design team by providing visible, consistent standards referenced across deliverables throughout org.',
    ],
    skills: [
      { name:'Strategy and Governance', pct:90 }, { name:'Cross-Leadership Comms', pct:92 }, { name:'Systemic Scaling of Designs', pct:88 },
      { name:'Migration Planning', pct:80 }, { name:'Designer Empowerment through Mentorship', pct:85 }, { name:'Outcome driven roadmap', pct:75 },
    ],
    quote: { text:'This new system changed how we work. Delivery time was cut by roughly 50%. Visual and interaction quality jumped by about 80%. We went from weeks assembling concepts to delivering clean, standardized prototypes in days or faster. It raised the bar for every project.\u201d', attr:'\u2014 Senior UX Designer | Plexus Worldwide' },
    deliveryDate: 'Q3 2024',
    galleryImages: [
      'https://images.unsplash.com/photo-1551288049-bebda4e38f71?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxkYXRhJTIwYW5hbHl0aWNzJTIwZGFzaGJvYXJkJTIwZGFyayUyMHNjcmVlbnxlbnwxfHx8fDE3NzIzNDQ5NDB8MA&ixlib=rb-4.1.0&q=80&w=1080',
      'https://images.unsplash.com/photo-1763038311036-6d18805537e5?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxidXNpbmVzcyUyMGludGVsbGlnZW5jZSUyMGRhdGElMjB2aXN1YWxpemF0aW9ufGVufDF8fHx8MTc3MjM0NDk0MHww&ixlib=rb-4.1.0&q=80&w=1080',
      'https://images.unsplash.com/photo-1686061593213-98dad7c599b9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxkYXRhYmFzZSUyMHF1ZXJ5JTIwU1FMJTIwcGVyZm9ybWFuY2UlMjBtb25pdG9yaW5nfGVufDF8fHx8MTc3MjM0NDk3OXww&ixlib=rb-4.1.0&q=80&w=1080',
      'https://images.unsplash.com/photo-1700827665658-842e5af5d140?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxBUEklMjBpbnRlZ3JhdGlvbiUyMHNvZnR3YXJlJTIwYXJjaGl0ZWN0dXJlfGVufDF8fHx8MTc3MjM0NDk0MHww&ixlib=rb-4.1.0&q=80&w=1080',
    ],
  },
  {
    id: 2,
    title: 'Membership Join Experience',
    status: 'In Progress',
    statusClass: 'chip-inprogress',
    category: 'CX Strategy \u00b7 Plexus Worldwide',
    bgGradient: 'linear-gradient(135deg,#2E1A47 0%,#4A2C6B 60%,#7A50A0 100%)',
    image: 'https://images.unsplash.com/photo-1681993302983-96d079223a70?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjdXN0b21lciUyMGV4cGVyaWVuY2UlMjBzdHJhdGVneSUyMG1lZXRpbmd8ZW58MXx8fHwxNzcxOTk0Mjk3fDA&ixlib=rb-4.1.0&q=80&w=1080',
    imagePosition: 'center',
    detailImagePosition: 'center',
    imageFit: 'cover',
    icon: 'sentiment_satisfied_alt',
    completion: 78,
    tags: ['Conversion UX','Trusted Growth Design','Network-Driven Commerce','Revenue growth','Ethic Flow Design'],
    desc: 'Defining modernization, common expectations, new customer flows, UI design, and how it benefits business goals in near and long terms.',
    progressLabel: 'In progress',
    progressValue: '78%',
    stats: [
      { icon: 'touch_app', label: 'Increase Ease of Use' },
      { icon: 'star_outline', label: 'Customer endorsement' },
      { icon: 'trending_down', label: 'Lower time and effort' },
    ],
    kpis: [
      { val:'+42', label:'Target NPS Increase' },
      { val:'9', label:'Touchpoints Redesigned' },
      { val:'31%', label:'Projected Churn \u2193' },
      { val:'Q2 2026', label:'Target Completion' },
    ],
    overview: 'This initiative reframes membership as a guided progression rather than a transactional gate. Accomplished by aligning interaction design, social platforms, and subscription mechanics across landing pages, cart, and checkout. The experience is designed to encourage first-time visitors to join with a product subscription and confidently move toward sharing the business. The result is to be a scalable foundation that improves conversion, reduces abandonment at critical moments, and supports sustainable entrepreneurial growth in each member.',
    challenge: 'I\u2019ve defined the experience strategy and design for a new membership join flows and entrepreneurial advancement. The core challenge is twofold: making it genuinely easy for new and existing members to join in compliance with company requirements, and ensuring prospective members clearly understand the value of both the products and the business opportunity\u2014without confusion, friction, or mistrust.',
    phases: [
      { icon:'search', label:'Problem Framing & Risk Identification', status:'Done', statusBg:'rgba(76,175,130,0.12)', statusColor:'#2E7D53' },
      { icon:'lightbulb', label:'Experience Strategy & Growth Alignment', status:'Done', statusBg:'rgba(76,175,130,0.12)', statusColor:'#2E7D53' },
      { icon:'build', label:'Interaction & Flow Redesign', status:'Done', statusBg:'rgba(76,175,130,0.12)', statusColor:'#2E7D53' },
      { icon:'phone_iphone', label:'Subscription-First Enablement', status:'In Progress', statusBg:'rgba(255,167,38,0.12)', statusColor:'#E65100' },
      { icon:'rocket_launch', label:'Delivery & Cross-team On-Boarding', status:'Planned', statusBg:'rgba(66,165,245,0.12)', statusColor:'#1565C0' },
    ],
    outcomes: [
      'Clarified membership value proposition, reducing hesitation and confusion at tier selection.',
      'Improved trust and transparency in cart and checkout through clearer expectations and guided success states.',
      'Enabled subscription-led membership activation as a first-class experience rather than an optional afterthought.',
      'Reduced friction for members advancing toward entrepreneurial participation and business sharing.',
      'Established a scalable join and advancement framework aligned with long-term retention and growth.',
    ],
    skills: [
      { name:'Strategy and roadmap ownership', pct:95 }, { name:'Conversion Interaction Design', pct:92 }, { name:'Retention journeys', pct:90 },
      { name:'Leadership Alignment', pct:82 }, { name:'Behavioral UX', pct:88 }, { name:'A/B Testing', pct:85 },
    ],
    quote: { text:'By simplifying the membership journey and aligning it with subscription-based product engagement, we plan to reduce effort at the most fragile points of conversion. Early analysis shows faster completion times, higher subscription attachment at join, and improved confidence\u2014an update that can potentially support both revenue and long-term success.', attr:'\u2014 VP of Sales | Plexus Worldwide' },
    deliveryDate: 'Q2 2026',
    galleryImages: [
      'https://loveadmin.com/wp-content/uploads/2022/03/member-journey-map-template.png',
      'https://cdn.prod.website-files.com/649ae86ac1a4be707b656519/670fcc9ebda2c7454af4aa56_01.webp',
      'https://higherlogicdownload.s3.amazonaws.com/ASSOCIATIONFORUM/57450e74-a1a5-439e-957f-9d9fde93d515/UploadedImages/Membership/MEMBERSHIP_Infographic.jpg',
      'https://www.slideteam.net/media/catalog/product/cache/1280x720/u/s/user_onboarding_process_flow_chart_slide01.jpg',
    ],
  },
  {
    id: 3,
    title: 'Live Metallurgy Dashboard',
    status: 'Delivered',
    statusClass: 'chip-delivered',
    category: 'Mining Tech \u00b7 Freeport McMoRan',
    bgGradient: 'linear-gradient(135deg,#1A2F1A 0%,#2E5A2E 60%,#4CAF82 100%)',
    image: 'https://cdn.myportfolio.com/abc1e0ab-7370-4502-8c78-92428397bf66/02e2cd4c-ce53-4c35-8142-7432c0e2b62e.png?h=ce460ffd3f8afeafa8a8f2016d5b9f01',
    imagePosition: 'top',
    detailImagePosition: 'top',
    imageFit: 'cover',
    icon: 'health_and_safety',
    completion: 100,
    tags: ['Industrial UX','Simulations Modeling','Compliance-Grade Visualization','Unified Global Operations','Scientific Data Support'],
    desc: 'Data driven array of live data points with-in metallurgical separation process that captures process efficacy, waste, opportunities, and scaling operations.',
    progressLabel: 'Completion',
    progressValue: '100%',
    stats: [
      { icon: 'local_hospital', label: 'Reduce Workforce Risks' },
      { icon: 'timer', label: 'Descrease time to profit' },
      { icon: 'star', label: '100% adoption rate' },
    ],
    kpis: [
      { val:'4-9%', label:'purity increases' },
      { val:'5', label:'Global Laboratory sites' },
      { val:'.015%', label:'Negligible variance' },
      { val:'12k Tonnes', label:'Monthly increase in High-grade molybdenum' },
    ],
    overview: 'A web-based application unifying live inputs, historical analysis, and scenario-based simulations to enable rapid, high-confidence operational decisions. By translating complex metallurgical data into an accessible, decision-ready interface, the platform materially improved purity outcomes, accelerated response time, and restored executive confidence in revenue forecasting tied to high-grade output.',
    challenge: 'I led the design of a global KPI and simulation platform used daily by chemists, process engineers, and regulatory stakeholders to optimize molybdenum purity alongside copper extraction. The platform addressed a critical business risk: declining market share driven by the increasing difficulty of achieving high-purity molybdenum required for medical, semiconductor, and advanced industrial applications under tightening regulatory standards.',
    phases: [
      { icon:'groups', label:'Partnered to Align Problem Framing', status:'Done', statusBg:'rgba(76,175,130,0.12)', statusColor:'#2E7D53' },
      { icon:'architecture', label:'Architecture for Data & Simulation', status:'Done', statusBg:'rgba(76,175,130,0.12)', statusColor:'#2E7D53' },
      { icon:'design_services', label:'UX for Complex Decision Mapping', status:'Done', statusBg:'rgba(76,175,130,0.12)', statusColor:'#2E7D53' },
      { icon:'bug_report', label:'Scenario Modeling & Communications', status:'Done', statusBg:'rgba(76,175,130,0.12)', statusColor:'#2E7D53' },
      { icon:'rocket_launch', label:'Global Adoption & Validation', status:'Done', statusBg:'rgba(76,175,130,0.12)', statusColor:'#2E7D53' },
    ],
    outcomes: [
      'Extraction strategies adjusted based on real-time and simulated purity outcomes.',
      'Standardized geographically distributed mining and laboratory environments.',
      'Simulation reduced operational uncertainty and rework by aligning real-world sensor results.',
      'Improved regulatory confidence through transparent, traceable purity and compliance data.',
      'UX delivered direct consequence to improved revenue protection and market competitiveness.',
    ],
    skills: [
      { name:'Complex data abstraction', pct:88 }, { name:'Intesive data and visual infographics', pct:90 }, { name:'Leadership in regulatory environments', pct:92 },
      { name:'Design for actionable communications', pct:95 }, { name:'Global Adoption Srategy', pct:75 }, { name:'Usability Interview testing', pct:90 },
    ],
    quote: { text:'It changed how we operate. Decisions that once took multiple shifts now happen in real time, directly protecting revenue. Purity improvements of 4\u20139%, reduced adjustment cycles from days to minutes, and achieved simulation accuracy within 0.015% variance of actual output, proving the highest purity standards.', attr:'\u2014 Chief Chemist | Freeport Rozenburg Rotterdam Plant' },
    deliveryDate: 'Q3 2024',
    galleryImages: [
      'https://cdn.myportfolio.com/abc1e0ab-7370-4502-8c78-92428397bf66/b5c07cf9-4947-4c10-a88e-b589c556a9db.png?h=6a934611881795653258e97a12f8f210',
      'https://cdn.myportfolio.com/abc1e0ab-7370-4502-8c78-92428397bf66/e9639116-9737-45a8-bc5a-720a401de5d8.png?h=50cc4aac0fa6e39f6b55967acf8af22e',
      'https://cdn.myportfolio.com/abc1e0ab-7370-4502-8c78-92428397bf66/248dc854-50ca-413a-96f1-4a40aeaa44a1.png?h=93ae70c04b993799e722dca19d90b938',
      'https://cdn.myportfolio.com/abc1e0ab-7370-4502-8c78-92428397bf66/697b238a-4114-4fbc-bb2d-7281a109467d.png?h=8f545811cc62c607043290ff65d3420f',
    ],
  },
  {
    id: 4,
    title: 'Cart & Checkout',
    status: 'In Progress',
    statusClass: 'chip-inprogress',
    category: 'E-Commerce \u00b7 Retail Operations',
    bgGradient: 'linear-gradient(135deg,#2A1A0A 0%,#6B4C1A 60%,#C9873A 100%)',
    image: 'https://images.unsplash.com/photo-1764795849833-6e9d6e399a77?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxyZXRhaWwlMjBzdG9yZSUyMG9wZXJhdGlvbnMlMjB0ZWNobm9sb2d5fGVufDF8fHx8MTc3MTk5NDI5N3ww&ixlib=rb-4.1.0&q=80&w=1080',
    imagePosition: 'center',
    detailImagePosition: 'center',
    imageFit: 'cover',
    icon: 'storefront',
    completion: 55,
    tags: ['Critical Conversion','Tranparent Commerce Design','Revenue capture','Modern Expectations','Growth Strategy'],
    desc: 'Leading Design, Product, and Marketing Teams to deliver UX improvements based on quantitaive analysis of customer interactions via A/B tests, surveys, business goals and customer needs. Targeting ease of use and lowering complexity.',
    progressLabel: 'Completion',
    progressValue: '55%',
    stats: [
      { icon: 'store', label: '200,000+ customers' },
      { icon: 'merge_type', label: 'Fast to Market: Target' },
      { icon: 'inventory_2', label: 'CX and usability' },
    ],
    kpis: [
      { val:'200k +', label:'monthly cart interactions' },
      { val:'15%', label:'Less abandonment' },
      { val:'Transparency', label:'Trust in experience' },
      { val:'Q4 \'26', label:'Target Go-Live' },
    ],
    overview: 'Restoring trust, reducing cognitive load, and enabling revenue-positive behaviors directly within the cart experience, including subscriptions, upsell, and frictionless express checkout. Partnering closely with executive leadership, PMO, and engineering, I established a design-led roadmap that aligns interaction decisions with business outcomes\u2014balancing speed, clarity, and monetization while setting a scalable foundation for future growth',
    challenge: 'I am leading the end-to-end refactoring of cart and checkout for a high-growth e-commerce supplement company facing critical revenue leakage driven by extreme cart and checkout abandonment. With abandonment exceeding 80%, declining customer trust, and checkout flows that diverged significantly from modern retail standards, the initiative was positioned as a business recovery effort\u2014not a visual refresh.',
    phases: [
      { icon:'search', label:'Problem & Signal Analysis', status:'Done', statusBg:'rgba(76,175,130,0.12)', statusColor:'#2E7D53' },
      { icon:'architecture', label:'Strategy & Roadmapping', status:'Done', statusBg:'rgba(76,175,130,0.12)', statusColor:'#2E7D53' },
      { icon:'point_of_sale', label:'Interaction & Flow Simplification', status:'In Progress', statusBg:'rgba(255,167,38,0.12)', statusColor:'#E65100' },
      { icon:'integration_instructions', label:'Systemization & Pattern Design', status:'In Progress', statusBg:'rgba(255,167,38,0.12)', statusColor:'#E65100' },
      { icon:'store', label:'Validation & Delivery Alignment', status:'Planned', statusBg:'rgba(66,165,245,0.12)', statusColor:'#1565C0' },
    ],
    outcomes: [
      'Clear, confidence-driven cart experience that addresses customer uncertainty at the point of purchase.',
      'Reduced effort in checkout flows and eliminating unnecessary steps and ambiguity.',
      'Enabled subscriptions as a first-class action directly within cart.',
      'Parity with modern retail UX standards, closing the gap with top-performing competitors.',
      'Growth in revenue, retention, and trust metrics through isolated UI improvements.',
    ],
    skills: [
      { name:'Strategy Ownership', pct:88 }, { name:'Behavioral UX design', pct:82 }, { name:'Cross-team Leadership', pct:78 },
      { name:'Business-driven Design', pct:80 }, { name:'Stategic Systemic Flows', pct:88 }, { name:'Executive Communications', pct:85 },
    ],
    quote: { text:'Reframing cart and checkout as a growth system rather than a technical necessity, based on early validations, expects meaningful reductions in abandonment, faster checkout completion, and a measurable lift in membership and subscription adoption\u2014directly impacting revenue and customer trust.', attr:'\u2014 Chief Strategy Officer | Plexus worldwide' },
    deliveryDate: 'Q4 2025',
    galleryImages: [
      'https://images.unsplash.com/photo-1746723378067-83a345ff3160?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxyZXRhaWwlMjBjaGVja291dCUyMHJlZ2lzdGVyJTIwbW9kZXJuJTIwdGVjaG5vbG9neXxlbnwxfHx8fDE3NzIzNDQ5Nzl8MA&ixlib=rb-4.1.0&q=80&w=1080',
      'https://images.unsplash.com/photo-1770910195585-825a1181a704?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx3YXJlaG91c2UlMjBpbnZlbnRvcnklMjBtYW5hZ2VtZW50JTIwc3lzdGVtfGVufDF8fHx8MTc3MjM0NDk0OXww&ixlib=rb-4.1.0&q=80&w=1080',
      'https://images.unsplash.com/photo-1768884919500-1d567af12afb?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzdG9yZSUyMHNoZWxmJTIwcHJvZHVjdCUyMGRpc3BsYXklMjBjb21tZXJjaWFsfGVufDF8fHx8MTc3MjM0NDk3OXww&ixlib=rb-4.1.0&q=80&w=1080',
      'https://images.unsplash.com/photo-1554769944-3138b076c38a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzdXBwbHklMjBjaGFpbiUyMGxvZ2lzdGljcyUyMGRhdGElMjBpbnRlZ3JhdGlvbnxlbnwxfHx8fDE3NzIzNDQ5NTB8MA&ixlib=rb-4.1.0&q=80&w=1080',
    ],
  },
  {
    id: 5,
    title: 'AI Driven Content Search',
    status: 'Planned',
    statusClass: 'chip-planned',
    category: 'EdTech \u00b7 Adaptive Learning',
    bgGradient: 'linear-gradient(135deg,#0A0A2A 0%,#1A1A4A 60%,#3A3A8A 100%)',
    image: 'https://images.unsplash.com/photo-1695473507908-ff60e604c113?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxlZHVjYXRpb24lMjBhZGFwdGl2ZSUyMGxlYXJuaW5nJTIwdGVjaG5vbG9neXxlbnwxfHx8fDE3NzE5OTQyOTh8MA&ixlib=rb-4.1.0&q=80&w=1080',
    imagePosition: 'center',
    detailImagePosition: 'center',
    imageFit: 'cover',
    icon: 'school',
    completion: 12,
    tags: ['ntelligent Search UX','AI-Assisted Design','Brand Confidence','CX Strategy','Consumer Ease'],
    desc: 'Creating a less ambiguous experience and more exact SERP that promotes less time to desired results and quicker descisions.',
    progressLabel: 'Planned Start',
    progressValue: 'Q3 2026',
    stats: [
      { icon: 'people', label: 'AI Trust Risks' },
      { icon: 'psychology', label: 'SEO GEO AGO Optimization' },
      { icon: 'trending_up', label: '95% Accuracy' },
    ],
    kpis: [
      { val:'AI', label:'smart search results' },
      { val:'99%', label:'accuracy in SERP' },
      { val:'+15%', label:'revenue and growth' },
      { val:'Q1 2027', label:'Official Kickoff Date' },
    ],
    overview: 'Search is a core customer experience layer, not a utility. By combining deterministic relevance logic with a custom AI API layer, the new system is designed to deliver exact, high-confidence results in the top positions, guide users when intent was unclear, and intelligently surface recommendations that accelerate cart, checkout, subscription, and membership actions. The result target a scalable search foundation that improves findability, reduces effort, and supports revenue-driving behaviors.',
    challenge: 'I am leading the experience strategy and design for a new embedded sitewide intelligent search component to address a critical trust and relevance failure in the company\u2019s existing search experience. Legacy search returned inaccurate, randomly matched results, forcing users to rely on external search engines to find products, content, and answers\u2014directly undermining confidence, conversion, and membership growth.',
    phases: [
      { icon:'search', label:'Problem Diagnosis & Signal Analysis', status:'In Progress', statusBg:'rgba(255,167,38,0.12)', statusColor:'#E65100' },
      { icon:'psychology', label:'Search Strategy & Experience Definition', status:'Planned', statusBg:'rgba(66,165,245,0.12)', statusColor:'#1565C0' },
      { icon:'design_services', label:'Architecture & Indexing Alignment', status:'Planned', statusBg:'rgba(66,165,245,0.12)', statusColor:'#1565C0' },
      { icon:'science', label:'Interaction Design & AI Guardrails', status:'Planned', statusBg:'rgba(66,165,245,0.12)', statusColor:'#1565C0' },
      { icon:'rocket_launch', label:'Prototype, Validation & Delivery', status:'Planned', statusBg:'rgba(66,165,245,0.12)', statusColor:'#1565C0' },
    ],
    outcomes: [
      'Restore trust in on-site search by prioritizing exact, intent-matched results in the most visible positions.',
      'Reduce user effort by guiding searches that yield ambiguous or no results rather than failing silently.',
      'Accelerate paths to cart and checkout through intelligent product recommendations and upsell logic.',
      'Unify discovery across products, content, support, and business resources into a single, coherent experience.',
      'Establish search as a strategic member tool, and growth lever supporting subscriptions, membership, and retention.',
    ],
    skills: [
      { name:'Platform-level Strategy', pct:80 }, { name:'AI-assisted code design', pct:75 }, { name:'CX decision-making', pct:90 },
      { name:'Journey and flow orchestration', pct:85 }, { name:'Cross-functional alignment', pct:72 }, { name:'Results-driven planning', pct:88 },
    ],
    quote: { text:'By rebuilding search around relevance and intent rather than keywords alone, we potentially reduce friction at the earliest stage of the journey. Early validation shows faster time-to-product, clearer paths to subscription and membership, and meaningful efficiency gains across conversion flows\u2014positioning search as a direct contributor to revenue and customer confidence.', attr:'\u2014 Direct of Digital Eperiences | Plexus Worldwide.' },
    deliveryDate: 'Q1 2027',
    galleryImages: [
      'https://images.unsplash.com/photo-1620067285935-ead87c731296?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxhZGFwdGl2ZSUyMGxlYXJuaW5nJTIwc3R1ZGVudCUyMGxhcHRvcCUyMGVkdWNhdGlvbnxlbnwxfHx8fDE3NzIzNDQ5NTN8MA&ixlib=rb-4.1.0&q=80&w=1080',
      'https://images.unsplash.com/photo-1758270704534-fd9715bffc0e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx1bml2ZXJzaXR5JTIwbGVjdHVyZSUyMGhhbGwlMjB0ZWNobm9sb2d5JTIwY2xhc3Nyb29tfGVufDF8fHx8MTc3MjM0NDk1MXww&ixlib=rb-4.1.0&q=80&w=1080',
      'https://images.unsplash.com/photo-1717502085413-478382daf23f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtYWNoaW5lJTIwbGVhcm5pbmclMjBhbGdvcml0aG0lMjBuZXVyYWwlMjBuZXR3b3JrfGVufDF8fHx8MTc3MjM0NDk1MXww&ixlib=rb-4.1.0&q=80&w=1080',
      'https://images.unsplash.com/photo-1673515335586-f9f662c01482?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxvbmxpbmUlMjBlZHVjYXRpb24lMjBwbGF0Zm9ybSUyMGRhc2hib2FyZCUyMGluc3RydWN0b3J8ZW58MXx8fHwxNzcyMzQ0OTU0fDA&ixlib=rb-4.1.0&q=80&w=1080',
    ],
  },
];

export const studies: Study[] = [
  {
    id: 0,
    title: 'CAD and 3D Design',
    category: 'Bachelor Degree',
    institution: 'Carnegie Mellon University',
    period: '2002\u20132005',
    bgGradient: 'linear-gradient(135deg,#0D7A87 0%,#1B9AAA 60%,#2BBDCF 100%)',
    image: 'https://images.unsplash.com/photo-1756973229525-53fbc1303a61?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx1bml2ZXJzaXR5JTIwY2FtcHVzJTIwZ3JhZHVhdGUlMjBzdHVkZW50fGVufDF8fHx8MTc3MTk5NDI5OHww&ixlib=rb-4.1.0&q=80&w=1080',
    imagePosition: 'center',
    detailImagePosition: 'center',
    imageFit: 'cover',
    icon: 'school',
    score: '3.4 / 4.0',
    scorePct: 98,
    tags: ['HCI','Visual Communication','Interaction Design','Research & Analysis','Problem phrasing'],
    desc: 'Walked away with a cause \u2192 effect \u2192 consequence foundation that has guided designing for outcome, performance, and intuition',
    overview: 'Early exposure to systems thinking and troubleshooting as a pathway to learn code shaped a practical understanding of how software actually works \u2014 not just how it\u2019s specified. Computer Aided Design and 3D modeling developed instincts in real life problem solving scenarios: urgency, clarity, failure states, and trust. I strengthened my command of visual communication, narrative flow, and critique-driven iteration to drive student projects and even tutor fellow students.',
    thesis: 'Along side of my learning interst was a profound curiosity of human psychology and behavior. Later using this as a primary force to solve problems.',
    modules: ['Technical Software Aptitude','Cognitive Foundations of HCI','User Research & Evaluation','Prototyping & Fabrication','Accessible & Inclusive Design','HCI Research Methods','Seminar in Design Theory'],
    skills: [
      { name:'Cognitive Design', pct:95 }, { name:'Research Methods', pct:96 }, { name:'Prototyping', pct:90 },
      { name:'Inclusive Design', pct:88 }, { name:'Academic Writing', pct:85 }, { name:'Statistical Analysis', pct:80 },
    ],
    highlight: 'Portfolio - Best in Show as voted by peers',
  },
  {
    id: 1,
    title: 'A+ and Network+',
    category: 'Information technology',
    institution: 'CompTIA',
    period: '2006\u20132008',
    bgGradient: 'linear-gradient(135deg,#1A2A4A 0%,#2E4A7A 60%,#4A7CC0 100%)',
    image: 'https://images.unsplash.com/photo-1675495277087-10598bf7bcd1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjb21wdXRlciUyMHNjaWVuY2UlMjBjb2RpbmclMjBwcm9ncmFtbWluZ3xlbnwxfHx8fDE3NzE5OTQyOTl8MA&ixlib=rb-4.1.0&q=80&w=1080',
    imagePosition: 'center',
    detailImagePosition: 'center',
    imageFit: 'cover',
    icon: 'computer',
    score: '827 / 900',
    scorePct: 95,
    tags: ['Algorithms','Data Structures','Systems','Software Engineering','Web Dev'],
    desc: 'Achieved certifications for retail technician and helpdesk opetations. Utilized knowledge to deliver graphic workstations for (in their day) heavy CGI rendering.',
    overview: 'Achieved certifications for retail technician and helpdesk operations. Utilized knowledge to deliver graphic workstations for heavy CGI rendering.',
    thesis: 'Hands-on experience with hardware diagnostics, network configuration, and troubleshooting methodologies.',
    modules: ['Hardware Diagnostics','Network Configuration','Operating Systems','Troubleshooting Methods','Security Fundamentals','Customer Support','System Administration','Peripheral Integration'],
    skills: [
      { name:'Algorithms', pct:88 }, { name:'C/C++', pct:80 }, { name:'Systems Programming', pct:78 },
      { name:'JavaScript', pct:85 }, { name:'SQL/Databases', pct:82 }, { name:'Software Engineering', pct:86 },
    ],
    highlight: 'CompTIA Certified \u2014 A+ and Network+ Credentials',
  },
  {
    id: 2,
    title: 'Communication in Vague Environments',
    category: 'Linked in Learning Certificates',
    institution: 'LinkedIn Learning',
    period: '2020-2025',
    bgGradient: 'linear-gradient(135deg,#2A4A2A 0%,#3A6A3A 60%,#5A9A5A 100%)',
    image: 'https://images.unsplash.com/photo-1586296835409-fe3fe6b35b56?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxVWCUyMGRlc2lnbiUyMHByb3RvdHlwZSUyMHNrZXRjaHxlbnwxfHx8fDE3NzE5OTQzMDN8MA&ixlib=rb-4.1.0&q=80&w=1080',
    imagePosition: 'center',
    detailImagePosition: 'center',
    imageFit: 'cover',
    icon: 'verified_user',
    score: '90-97%',
    scorePct: 97,
    tags: ['Empathy Mapping','Wireframing','Prototyping','Usability Testing','Portfolio'],
    desc: 'Self guided courses to elicit deep functional understanding of behaviors, methods, and philosophy to communicate in stressful or contentious environments.',
    overview: 'Self guided courses to elicit deep functional understanding of behaviors, methods, and philosophy to communicate in stressful or contentious environments.',
    thesis: 'Focused on navigating ambiguity, building consensus, and driving alignment across diverse stakeholder groups.',
    modules: ['Foundations of UX Design','Start the UX Design Process','Build Wireframes & Low-Fi Prototypes','Conduct UX Research','Create High-Fi Designs in Figma','Responsive Web Design','Design a UX Portfolio'],
    skills: [
      { name:'Figma', pct:96 }, { name:'Usability Testing', pct:90 }, { name:'Wireframing', pct:94 },
      { name:'Affinity Diagramming', pct:88 }, { name:'Competitive Analysis', pct:85 }, { name:'Portfolio Writing', pct:82 },
    ],
    highlight: 'Multiple certificates across communication and leadership tracks',
  },
  {
    id: 3,
    title: 'Project Management and Agile workflows',
    category: 'Nasba',
    institution: 'NASBA',
    period: '2022',
    bgGradient: 'linear-gradient(135deg,#4A3A1A 0%,#8A6A2A 60%,#C9A03A 100%)',
    image: 'https://images.unsplash.com/photo-1506399558188-acca6f8cbf41?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjbG91ZCUyMGNvbXB1dGluZyUyMHNlcnZlciUyMGluZnJhc3RydWN0dXJlfGVufDF8fHx8MTc3MTk5NDMwMHww&ixlib=rb-4.1.0&q=80&w=1080',
    imagePosition: 'center',
    detailImagePosition: 'center',
    imageFit: 'cover',
    icon: 'cloud_queue',
    score: '891 / 1000',
    scorePct: 89,
    tags: ['AWS','Cloud Architecture','VPC','Serverless','Security','IAM'],
    desc: 'Gained the knowledge to push my skills to develop how to profesionaly make deliverables, requirements, analysis, and strategies that achieve goals.',
    overview: 'Gained the knowledge to push my skills to develop how to professionally make deliverables, requirements, analysis, and strategies that achieve goals.',
    thesis: 'Focus on Agile methodologies, sprint planning, risk assessment, and stakeholder communication.',
    modules: ['EC2 & Compute Services','S3 & Storage','VPC Networking','RDS & Database Services','Serverless (Lambda, API Gateway)','CloudFormation / IaC','IAM & Security Best Practices','Cost Optimisation'],
    skills: [
      { name:'AWS Architecture', pct:87 }, { name:'VPC & Networking', pct:83 }, { name:'IAM & Security', pct:85 },
      { name:'Serverless', pct:80 }, { name:'Cost Optimisation', pct:78 }, { name:'IaC (CloudFormation)', pct:75 },
    ],
    highlight: 'Score: 891/1000 \u2014 NASBA accredited certification',
  },
  {
    id: 4,
    title: 'TestMu AI Test Automation Certificate',
    category: 'LambaTest',
    institution: 'LambdaTest',
    period: '2024',
    bgGradient: 'linear-gradient(135deg,#1A1A4A 0%,#2A2A7A 60%,#4A4AB0 100%)',
    image: 'https://images.unsplash.com/photo-1770169272345-9636d5ef2681?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtYWNoaW5lJTIwbGVhcm5pbmclMjBuZXVyYWwlMjBuZXR3b3JrJTIwYWJzdHJhY3R8ZW58MXx8fHwxNzcxOTk0Mjk5fDA&ixlib=rb-4.1.0&q=80&w=1080',
    imagePosition: 'center',
    detailImagePosition: 'center',
    imageFit: 'cover',
    icon: 'psychology',
    score: '100%',
    scorePct: 100,
    tags: ['Supervised Learning','Neural Networks','Unsupervised Learning','Reinforcement Learning','Python'],
    desc: 'Expanded my knowledge of operational quality and scalabilty. Hands-on familiarity with AI-driven test creation, maintenance, and execution.',
    overview: 'Expanded my knowledge of operational quality and scalability. Hands-on familiarity with AI-driven test creation, maintenance, and execution.',
    thesis: 'Practical application of AI-driven testing methodologies for scalable quality assurance.',
    modules: ['Supervised Machine Learning: Regression & Classification','Advanced Learning Algorithms (Neural Nets, Decision Trees)','Unsupervised Learning, Recommenders & Reinforcement Learning'],
    skills: [
      { name:'Python / NumPy', pct:90 }, { name:'TensorFlow / Keras', pct:85 }, { name:'Scikit-learn', pct:88 },
      { name:'Neural Networks', pct:84 }, { name:'Recommender Systems', pct:87 }, { name:'Statistical ML', pct:82 },
    ],
    highlight: 'Perfect score \u2014 100% across all assessments',
  },
  {
    id: 5,
    title: 'Business, Data analysis and Software Development',
    category: 'Microsoft Credentials',
    institution: 'Microsoft',
    period: '2024',
    bgGradient: 'linear-gradient(135deg,#3A1A4A 0%,#6A2A7A 60%,#9A3AB0 100%)',
    image: 'https://images.unsplash.com/photo-1590402494811-8ffd29f17543?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwcm9kdWN0JTIwbWFuYWdlbWVudCUyMHJvYWRtYXAlMjB3aGl0ZWJvYXJkfGVufDF8fHx8MTc3MTk5NDMwMHww&ixlib=rb-4.1.0&q=80&w=1080',
    imagePosition: 'center',
    detailImagePosition: 'center',
    imageFit: 'cover',
    icon: 'inventory_2',
    score: '95%',
    scorePct: 95,
    tags: ['Product Strategy','OKRs','Roadmapping','Go-to-Market','Stakeholder Mgmt'],
    desc: 'Moved me from execution as an individual contributor to ownership of intiatives and to strategic design translation.',
    overview: 'Moved me from execution as an individual contributor to ownership of initiatives and to strategic design translation.',
    thesis: 'Bridging the gap between business analysis, data-driven decision making, and software development.',
    modules: ['Product Discovery & Validation','Writing PRDs & User Stories','Roadmap Prioritisation (RICE, ICE, Kano)','OKR Setting & Alignment','Go-to-Market Strategy','Metrics & Growth Loops','Stakeholder & Exec Communication','Technical PM Skills'],
    skills: [
      { name:'Product Strategy', pct:92 }, { name:'OKR Frameworks', pct:88 }, { name:'Prioritisation', pct:90 },
      { name:'Roadmapping', pct:90 }, { name:'GTM Strategy', pct:84 }, { name:'Exec Communication', pct:87 },
    ],
    highlight: '95% score \u2014 Microsoft Business, Data Analysis, and Software Development credentials',
  },
];

// searchIndex has been moved to /src/app/components/search-index.ts